### ISSUE TITLE
How much time and GPU consumed for the scene-agnostic NeRF-Loc across different scenes trainging? 

### ISSUE THREAD

**Issue by LZL-CS** [TencentYoutuResearch/NeRF-Loc#14]
Hi @JenningsL, 

May I know how much time and GPU resources are consumed when you train the scene-agnostic NeRF-Loc across different scenes? I used A100(40GB) to train scene-agnostic NeRF-Loc, but only 17 epochs were finished after around 130 hours. 

Is the time expected or I made some mistakes in this training process?

I appreciate any help you can provide!

**Comment by JenningsL** [comment]
The training time depends on number of training images. As far as I recall, training scene-agnostic model on Cambridge Landmarks for 30 epochs with 8 V100 GPUs cost 20~30 hours. However, the training speed could be affected by other reason such as IO. You may want to check the GPU utilities to see if there's a bottle neck in data-loading.

**Comment by LZL-CS** [comment]
> The training time depends on number of training images. As far as I recall, training scene-agnostic model on Cambridge Landmarks for 30 epochs with 8 V100 GPUs cost 20~30 hours. However, the training speed could be affected by other reason such as IO. You may want to check the GPU utilities to see if there's a bottle neck in data-loading.

Hi @JenningsL, thanks for your reply. I trained scene-agnostic NeRF-Loc across 7Scenes, which spent more than 5 days. I checked GPU utilities, which seems usual. About the data loading, do I need to modify something? Could you provide some suggestions?

**Comment by JenningsL** [comment]
It seems that you are using only one GPU for training. To reduce training time, I would recomend using more GPUs if possible. Here are some suggestions to save time, if you don't have access to more computing resources. 
1. Early stop.
2. Reduce the number of support images, since the most heavy part is the image backbone. You can even try to freeze the entire 2D backbone after a few epochs. 
3. Train with a random subset of the dataset for your early experiments.
Since the GPU utilities are high, data loading should not be the bottle neck. However, there are definitely a lots of rooms for efficiency optimization. I'm sorry that I can't not provide further help with that at the moment.

**Comment by LZL-CS** [comment]
> It seems that you are using only one GPU for training. To reduce training time, I would recomend using more GPUs if possible. Here are some suggestions to save time, if you don't have access to more computing resources.
> 
> 1. Early stop.
> 2. Reduce the number of support images, since the most heavy part is the image backbone. You can even try to freeze the entire 2D backbone after a few epochs.
> 3. Train with a random subset of the dataset for your early experiments.
>    Since the GPU utilities are high, data loading should not be the bottle neck. However, there are definitely a lots of rooms for efficiency optimization. I'm sorry that I can't not provide further help with that at the moment.

OK, got it. I will try other ways. And thanks fro your kind help! Have a nice day!
